services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "pass-me-pls"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    logging:
      options:
        max-size: "1024k"
        max-file: "5"
